/*
 * For font license information, see the CSS file loaded by this JavaScript.
 */
if(!window.Typekit)window.Typekit={};window.Typekit.config={"a":"418219","c":[".tk-lemonde-journal","\"lemonde-journal-1\",\"lemonde-journal-2\",serif",".tk-arvo","\"arvo-1\",\"arvo-2\",serif",".tk-liberation-serif","\"liberation-serif-1\",\"liberation-serif-2\",serif"],"f":"//use.typekit.net/c/7f39ad/1w;arvo-1,2,WXB:R:n4;lemonde-journal-1,2,NWc:R:n4;liberation-serif-1,2,MyX:R:i4,MyZ:R:i7,MyW:R:n4,MyY:R:n7/{format}{/extras*}?3bb2a6e53c9684ffdc9a9bf4195b2a62ac2abccc2253da0ff4783e8b08b8547d97d9bc5180f83e575f3b60f903b6c362b178198615804ac709f6e26a224dae9672e3c65c052f17fdafa66f03033d73fec2b1964bd68c488dac9322462c494df819ff37629518bb78e9f3c2e09e283dbc4853f9136d0c7aac7e358f","fi":[1883,9658,12,9,11,10],"fn":["arvo-1",["n4"],"lemonde-journal-1",["n4"],"liberation-serif-1",["i4","i7","n4","n7"]],"ht":"tk","k":"//use.typekit.net/{id}.js","kt":"ukv4sym","p":"//p.typekit.net/p.gif?s=1&k=ukv4sym&ht=tk&h={host}&f=1883.9658.12.9.11.10&a=418219&_={_}","ps":1,"w":"ukv4sym"};
/*{"k":"1.11.5","created":"2015-01-21 10:00:30 UTC"}*/
;(function(window,document,undefined){
function aa(a,b,c){return a.call.apply(a.bind,arguments)}function ba(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function h(a,b,c){h=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?aa:ba;return h.apply(null,arguments)}var ca=Date.now||function(){return+new Date};
function da(a,b){this.na=a;this.aa=b||a;this.H=this.aa.document}da.prototype.createElement=function(a,b,c){a=this.H.createElement(a);if(b)for(var d in b)b.hasOwnProperty(d)&&("style"==d?a.style.cssText=b[d]:a.setAttribute(d,b[d]));c&&a.appendChild(this.H.createTextNode(c));return a};function k(a,b,c){a=a.H.getElementsByTagName(b)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(c,a.lastChild)}function ea(a,b){function c(){a.H.body?b():setTimeout(c,0)}c()}
function l(a,b,c){b=b||[];c=c||[];for(var d=a.className.split(/\s+/),e=0;e<b.length;e+=1){for(var f=!1,g=0;g<d.length;g+=1)if(b[e]===d[g]){f=!0;break}f||d.push(b[e])}b=[];for(e=0;e<d.length;e+=1){f=!1;for(g=0;g<c.length;g+=1)if(d[e]===c[g]){f=!0;break}f||b.push(d[e])}a.className=b.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function fa(a,b){for(var c=a.className.split(/\s+/),d=0,e=c.length;d<e;d++)if(c[d]==b)return!0;return!1}
function n(a){if("string"===typeof a.qa)return a.qa;var b=a.aa.location.protocol;"about:"==b&&(b=a.na.location.protocol);return"https:"==b?"https:":"http:"}function ga(a,b){/^http(s)?:$/.test(b)&&(a.qa=b)}function ia(a){return a.aa.location.hostname||a.na.location.hostname}function ja(a,b){var c=a.createElement("link",{rel:"stylesheet",href:b}),d=!1;c.onload=function(){d||(d=!0)};c.onerror=function(){d||(d=!0)};k(a,"head",c)}
function ka(a,b,c){var d=a.H.getElementsByTagName("head")[0];if(d){var e=a.createElement("script",{src:b}),f=!1;e.onload=e.onreadystatechange=function(){f||this.readyState&&"loaded"!=this.readyState&&"complete"!=this.readyState||(f=!0,c&&c(null),e.onload=e.onreadystatechange=null,"HEAD"==e.parentNode.tagName&&d.removeChild(e))};d.appendChild(e);window.setTimeout(function(){f||(f=!0,c&&c(Error("Script load timeout")))},5E3)}}function p(a){this.va=a}
function r(a,b,c,d){this.m=null!=a?a:null;this.r=null!=b?b:null;this.O=null!=c?c:null;this.l=null!=d?d:null}var la=/^([0-9]+)(?:[\._-]([0-9]+))?(?:[\._-]([0-9]+))?(?:[\._+-]?(.*))?$/;r.prototype.compare=function(a){return this.m>a.m||this.m===a.m&&this.r>a.r||this.m===a.m&&this.r===a.r&&this.O>a.O?1:this.m<a.m||this.m===a.m&&this.r<a.r||this.m===a.m&&this.r===a.r&&this.O<a.O?-1:0};function s(a,b){return-1===a.compare(b)}function t(a,b){return 0===a.compare(b)||1===a.compare(b)}
function u(a,b){return 0===a.compare(b)}r.prototype.toString=function(){return[this.m,this.r||"",this.O||"",this.l||""].join("")};function w(a){a=la.exec(a);var b=null,c=null,d=null,e=null;a&&(null!==a[1]&&a[1]&&(b=parseInt(a[1],10)),null!==a[2]&&a[2]&&(c=parseInt(a[2],10)),null!==a[3]&&a[3]&&(d=parseInt(a[3],10)),null!==a[4]&&a[4]&&(e=/^[0-9]+$/.test(a[4])?parseInt(a[4],10):a[4]));return new r(b,c,d,e)}
function x(a,b,c,d,e,f,g,m){this.U=a;this.v=b;this.I=c;this.R=d;this.n=e;this.h=f;this.$=g;this.B=m}x.prototype.getName=function(){return this.U};function ma(a,b){this.e=a;this.Q=b}var na=new x("Unknown",new r,"Unknown",new r,"Unknown",new r,void 0,new p(!1));
ma.prototype.parse=function(){var a;if(-1!=this.e.indexOf("MSIE")||-1!=this.e.indexOf("Trident/")){a=y(this);var b=w(A(this)),c=null,d=null,e=null,e=B(this.e,/Trident\/([\d\w\.]+)/,1),f=C(this.Q),c=-1!=this.e.indexOf("MSIE")?w(B(this.e,/MSIE ([\d\w\.]+)/,1)):w(B(this.e,/rv:([\d\w\.]+)/,1));""!=e?(d="Trident",e=w(e)):(d="Unknown",e=new r);a=new x("MSIE",c,d,e,a,b,f,new p(!1))}else if(-1!=this.e.indexOf("Opera"))a:if(a="Unknown",b=w(B(this.e,/Presto\/([\d\w\.]+)/,1)),c=w(A(this)),d=C(this.Q),null!==
b.m?a="Presto":(-1!=this.e.indexOf("Gecko")&&(a="Gecko"),b=w(B(this.e,/rv:([^\)]+)/,1))),-1!=this.e.indexOf("Opera Mini/"))f=w(B(this.e,/Opera Mini\/([\d\.]+)/,1)),a=new x("OperaMini",f,a,b,y(this),c,d,new p(!1));else{if(-1!=this.e.indexOf("Version/")&&(f=w(B(this.e,/Version\/([\d\.]+)/,1)),null!==f.m)){a=new x("Opera",f,a,b,y(this),c,d,new p(!1));break a}f=w(B(this.e,/Opera[\/ ]([\d\.]+)/,1));a=null!==f.m?new x("Opera",f,a,b,y(this),c,d,new p(!1)):new x("Opera",new r,a,b,y(this),c,d,new p(!1))}else/OPR\/[\d.]+/.test(this.e)?
a=oa(this):/AppleWeb(K|k)it/.test(this.e)?a=oa(this):-1!=this.e.indexOf("Gecko")?(a="Unknown",b=new r,c=w(A(this)),-1!=this.e.indexOf("Firefox")?(a="Firefox",b=w(B(this.e,/Firefox\/([\d\w\.]+)/,1))):-1!=this.e.indexOf("Mozilla")&&(a="Mozilla"),d=w(B(this.e,/rv:([^\)]+)/,1)),a=new x(a,b,"Gecko",d,y(this),c,C(this.Q),new p(!1))):a=na;return a};
function y(a){var b=B(a.e,/(iPod|iPad|iPhone|Android|Windows Phone|BB\d{2}|BlackBerry)/,1);if(""!=b)return/BB\d{2}/.test(b)&&(b="BlackBerry"),b;a=B(a.e,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS|PlayStation|CrKey)/,1);return""!=a?("Mac_PowerPC"==a?a="Macintosh":"PlayStation"==a&&(a="Linux"),a):"Unknown"}
function A(a){var b=B(a.e,/(OS X|Windows NT|Android) ([^;)]+)/,2);if(b||(b=B(a.e,/Windows Phone( OS)? ([^;)]+)/,2))||(b=B(a.e,/(iPhone )?OS ([\d_]+)/,2)))return b;if(b=B(a.e,/(?:Linux|CrOS|CrKey) ([^;)]+)/,1))for(var b=b.split(/\s/),c=0;c<b.length;c+=1)if(/^[\d\._]+$/.test(b[c]))return b[c];return(a=B(a.e,/(BB\d{2}|BlackBerry).*?Version\/([^\s]*)/,2))?a:"Unknown"}
function oa(a){var b=y(a),c=w(A(a)),d=w(B(a.e,/AppleWeb(?:K|k)it\/([\d\.\+]+)/,1)),e="Unknown",f=new r,f="Unknown";/OPR\/[\d.]+/.test(a.e)?e="Opera":-1!=a.e.indexOf("Chrome")||-1!=a.e.indexOf("CrMo")||-1!=a.e.indexOf("CriOS")?e="Chrome":/Silk\/\d/.test(a.e)?e="Silk":"BlackBerry"==b||"Android"==b?e="BuiltinBrowser":-1!=a.e.indexOf("PhantomJS")?e="PhantomJS":-1!=a.e.indexOf("Safari")?e="Safari":-1!=a.e.indexOf("AdobeAIR")?e="AdobeAIR":-1!=a.e.indexOf("PlayStation")&&(e="BuiltinBrowser");"BuiltinBrowser"==
e?f="Unknown":"Silk"==e?f=B(a.e,/Silk\/([\d\._]+)/,1):"Chrome"==e?f=B(a.e,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2):-1!=a.e.indexOf("Version/")?f=B(a.e,/Version\/([\d\.\w]+)/,1):"AdobeAIR"==e?f=B(a.e,/AdobeAIR\/([\d\.]+)/,1):"Opera"==e?f=B(a.e,/OPR\/([\d.]+)/,1):"PhantomJS"==e&&(f=B(a.e,/PhantomJS\/([\d.]+)/,1));f=w(f);return new x(e,f,"AppleWebKit",d,b,c,C(a.Q),new p(536>d.m||536==d.m&&11>d.r))}function B(a,b,c){return(a=a.match(b))&&a[c]?a[c]:""}function C(a){if(a.documentMode)return a.documentMode}
function pa(a){this.Ea=a||"-"}pa.prototype.l=function(a){for(var b=[],c=0;c<arguments.length;c++)b.push(arguments[c].replace(/[\W_]+/g,"").toLowerCase());return b.join(this.Ea)};function qa(a,b,c,d,e){this.g=a;this.q=b;this.W=c;this.p="wf";this.o=new pa("-");this.za=!1!==d;this.F=!1!==e}function D(a){if(a.F){var b=fa(a.q,a.o.l(a.p,"active")),c=[],d=[a.o.l(a.p,"loading")];b||c.push(a.o.l(a.p,"inactive"));l(a.q,c,d)}E(a,"inactive")}
function E(a,b,c){if(a.za&&a.W[b])if(c)a.W[b](c.getName(),F(c));else a.W[b]()}function G(a,b){this.U=a;this.ca=4;this.V="n";var c=(b||"n4").match(/^([nio])([1-9])$/i);c&&(this.V=c[1],this.ca=parseInt(c[2],10))}G.prototype.getName=function(){return this.U};function F(a){return a.V+a.ca}function H(a,b){this.g=a;this.M=b;this.w=this.g.createElement("span",{"aria-hidden":"true"},this.M)}function ra(a){k(a.g,"body",a.w)}
function sa(a){var b;b=[];for(var c=a.U.split(/,\s*/),d=0;d<c.length;d++){var e=c[d].replace(/['"]/g,"");-1==e.indexOf(" ")?b.push(e):b.push("'"+e+"'")}b=b.join(",");c="normal";"o"===a.V?c="oblique":"i"===a.V&&(c="italic");return"display:block;position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;white-space:nowrap;font-family:"+b+";"+("font-style:"+c+";font-weight:"+(a.ca+"00")+";")}
H.prototype.remove=function(){var a=this.w;a.parentNode&&a.parentNode.removeChild(a)};function ta(a,b,c,d,e,f,g,m){this.da=a;this.Da=b;this.g=c;this.A=d;this.M=m||"BESbswy";this.B=e;this.N={};this.ba=f||3E3;this.oa=g||null;this.L=this.K=null;a=new H(this.g,this.M);ra(a);for(var v in I)I.hasOwnProperty(v)&&(b=new G(I[v],F(this.A)),b=sa(b),a.w.style.cssText=b,this.N[I[v]]=a.w.offsetWidth);a.remove()}var I={Sa:"serif",Ra:"sans-serif",Na:"monospace"};
ta.prototype.start=function(){this.K=new H(this.g,this.M);ra(this.K);this.L=new H(this.g,this.M);ra(this.L);this.Ia=ca();var a=new G(this.A.getName()+",serif",F(this.A)),a=sa(a);this.K.w.style.cssText=a;a=new G(this.A.getName()+",sans-serif",F(this.A));a=sa(a);this.L.w.style.cssText=a;ua(this)};function va(a,b,c){for(var d in I)if(I.hasOwnProperty(d)&&b===a.N[I[d]]&&c===a.N[I[d]])return!0;return!1}
function ua(a){var b=a.K.w.offsetWidth,c=a.L.w.offsetWidth;b===a.N.serif&&c===a.N["sans-serif"]||a.B.va&&va(a,b,c)?ca()-a.Ia>=a.ba?a.B.va&&va(a,b,c)&&(null===a.oa||a.oa.hasOwnProperty(a.A.getName()))?wa(a,a.da):wa(a,a.Da):xa(a):wa(a,a.da)}function xa(a){setTimeout(h(function(){ua(this)},a),25)}function wa(a,b){a.K.remove();a.L.remove();b(a.A)}function ya(a,b,c,d){this.g=b;this.C=c;this.Y=0;this.ua=this.ma=!1;this.ba=d;this.B=a.B}
ya.prototype.Aa=function(a){var b=this.C;b.F&&l(b.q,[b.o.l(b.p,a.getName(),F(a).toString(),"active")],[b.o.l(b.p,a.getName(),F(a).toString(),"loading"),b.o.l(b.p,a.getName(),F(a).toString(),"inactive")]);E(b,"fontactive",a);this.ua=!0;za(this)};
ya.prototype.Ba=function(a){var b=this.C;if(b.F){var c=fa(b.q,b.o.l(b.p,a.getName(),F(a).toString(),"active")),d=[],e=[b.o.l(b.p,a.getName(),F(a).toString(),"loading")];c||d.push(b.o.l(b.p,a.getName(),F(a).toString(),"inactive"));l(b.q,d,e)}E(b,"fontinactive",a);za(this)};function za(a){0==--a.Y&&a.ma&&(a.ua?(a=a.C,a.F&&l(a.q,[a.o.l(a.p,"active")],[a.o.l(a.p,"loading"),a.o.l(a.p,"inactive")]),E(a,"active")):D(a.C))}
function Aa(){var a=[{name:"font-family",value:J.c[K+1]}];this.Ga=[J.c[K]];this.ha=a}function Ba(a){for(var b=a.Ga.join(","),c=[],d=0;d<a.ha.length;d++){var e=a.ha[d];c.push(e.name+":"+e.value+";")}return b+"{"+c.join("")+"}"}function Ca(a){this.g=a}Ca.prototype.toString=function(){return encodeURIComponent(ia(this.g))};function Da(a,b){this.s=a;this.t=b}
Da.prototype.toString=function(){for(var a=[],b=0;b<this.t.length;b++)for(var c=this.t[b],d=c.D(),c=c.D(this.s),e=0;e<d.length;e++){var f;a:{for(f=0;f<c.length;f++)if(d[e]===c[f]){f=!0;break a}f=!1}a.push(f?1:0)}a=a.join("");a=a.replace(/^0+/,"");b=[];for(d=a.length;0<d;d-=4)b.unshift(parseInt(a.slice(0>d-4?0:d-4,d),2).toString(16));return b.join("")};function L(a){this.Ka=a}
L.prototype.l=function(a,b){var c=b||{},d=this.Ka.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,b,d){return d&&c[b]?"/"+c[b].join("/"):c[b]||""});d.match(/^\/\//)&&(d=(a?"https:":"http:")+d);return d.replace(/\/*\?*($|\?)/,"$1")};function Ea(a,b){for(var c=[],d=0;d<b.length;d++)c.push(b[d].toString());return{format:a,extras:c}}function Fa(a,b){this.J=a;this.S=b;this.ka={};this.ia={}}Fa.prototype.D=function(a){return a?(this.ka[a]||this.S).slice(0):this.S.slice(0)};
function Ga(a,b,c){for(var d=[],e=a.J.split(",")[0].replace(/"|'/g,""),f=a.D(),g,m=[],v={},q=0;q<f.length;q++)g=f[q],0<g.length&&!v[g]&&(v[g]=!0,m.push(g));c=c.ra?c.ra(e,m,d):m;a.ka[b]=c;a.ia[b]=d}function Ha(a,b){for(var c=a.D(b),d=a.ia[b]||[],e=[],f=0;f<c.length;f++)e.push(new G(a.J,c[f]));for(f=0;f<d.length;f++)if(c=d[f].J,c!==a.J)for(var g=d[f].D(),m=0;m<g.length;m++)e.push(new G(c,g[m]));return e}function Ia(a,b){this.J=a;this.S=b}Ia.prototype.D=function(){return this.S};
function Ja(a,b,c,d,e){this.Ha=a;this.Ca=b;this.ja=c||[];this.xa=d||null;this.Ja=e||null}Ja.prototype.send=function(a){this.ja.length&&Ka((new L("//p.typekit.net/p.gif?s={service}&k={token}&app={app}&ht={hosting}&h={host}&f={variations}&a={account}&_={_}")).l("https:"===n(a),{service:this.Ha,token:this.Ja,app:encodeURIComponent((window.__adobewebfontsappname__||"").toString().substr(0,20)),hosting:this.Ca,host:encodeURIComponent(ia(a)),variations:this.ja.join("."),account:this.xa,_:(+new Date).toString()}))};
function Ka(a){var b=new Image(1,1),c=!1;b.src=a;b.onload=function(){c=!0;b.onload=null};setTimeout(function(){c||(b.src="about:blank",b.onload=null)},3E3)}function La(){this.ea=this.wa=this.G=this.T=this.la=!0}function M(a){return"Windows"===a.n}function N(a){return M(a)&&u(a.h,new r(5,1))||M(a)&&u(a.h,new r(5,2))||M(a)&&u(a.h,new r(6,0))||M(a)&&t(a.h,new r(6,1))}function O(a){return"Macintosh"===a.n&&(t(a.h,new r(10,4))||null===a.h.m)}
function Ma(a,b){return b.la&&("iPhone"===a.n||"iPod"===a.n)}function Na(a,b){return Ma(a,b)&&t(a.h,new r(4,2))&&s(a.h,new r(5))}function Oa(a,b){return b.T&&"iPad"===a.n&&t(a.h,new r(4,2))&&s(a.h,new r(5))}function P(a,b){return b.G&&"Android"===a.n}function Pa(a,b){return P(a,b)&&t(a.h,new r(2,2))&&s(a.h,new r(3,1))}function Qa(a,b){return P(a,b)&&t(a.h,new r(3,1))&&s(a.h,new r(4,1))}function Q(a){return"Linux"===a.n||"Ubuntu"===a.n}
function Ra(a){return"Safari"===a.getName()&&"AppleWebKit"===a.I||"Unknown"===a.getName()&&"AppleWebKit"===a.I&&("iPhone"===a.n||"iPad"===a.n||"iPod"===a.n)}function Sa(a){return"Safari"===a.getName()&&"AppleWebKit"===a.I&&t(a.R,new r(525,13))&&s(a.R,new r(534,50))}function Ta(a){return"BuiltinBrowser"===a.getName()}function Ua(a){this.ra=a}function Va(a,b){return b}
var R={Oa:"a",Qa:"b",Ta:"d",Ma:"i",Pa:"j",La:"k",NONE:"x"},S={a:function(a,b){return Sa(a)&&N(a)||Ta(a)&&(Pa(a,b)||P(a,b)&&t(a.h,new r(4,1)))||b.G&&"Silk"===a.getName()&&s(a.v,new r(2))&&(Pa(a,b)||O)||b.G&&"Silk"===a.getName()&&t(a.v,new r(2))&&P(a,b)&&t(a.h,new r(4,1))||Ra(a)&&(Oa(a,b)||Na(a,b))||"Chrome"===a.getName()&&t(a.v,new r(6))&&(Oa(a,b)||Na(a,b))||"AdobeAIR"===a.getName()&&t(a.v,new r(2,5))&&(M(a)&&null===a.h.m||Q(a))},b:function(a){return Sa(a)&&O(a)||"AdobeAIR"===a.getName()&&t(a.v,new r(2,
5))&&O(a)},d:function(a,b){return"Chrome"===a.getName()&&t(a.v,new r(6))&&(N(a)||Q(a)||O(a)||P(a,b)||"CrOS"===a.n||"CrKey"===a.n||b.T&&"iPad"===a.n&&t(a.h,new r(5))||Ma(a,b)&&t(a.h,new r(5)))||"Gecko"===a.I&&1===a.R.compare(new r(1,9,1))&&(N(a)||Q(a)||O(a)||P(a,b))||"Safari"===a.getName()&&"AppleWebKit"===a.I&&t(a.R,new r(534,50))&&(N(a)||O(a))||Ra(a)&&(b.T&&"iPad"===a.n&&t(a.h,new r(5))||Ma(a,b)&&t(a.h,new r(5)))||"Opera"===a.getName()&&t(a.v,new r(11,10))&&(N(a)||Q(a)||O(a)||P(a,b))||"MSIE"===a.getName()&&
9<=a.$&&(M(a)&&t(a.h,new r(6,1))||M(a)&&u(a.h,new r(6,0)))||"MSIE"===a.getName()&&b.wa&&"Windows Phone"===a.n&&t(a.h,new r(8))||Ta(a)&&(b.ea&&"BlackBerry"===a.n&&t(a.h,new r(10))||Q(a))},j:function(a,b){return Ta(a)&&Qa(a,b)||b.G&&"Silk"===a.getName()&&t(a.v,new r(2))&&(Qa(a,b)||Q(a))},i:function(a){return"MSIE"===a.getName()&&t(a.v,new r(6,0))&&(void 0===a.$||9>a.$)&&N(a)},x:function(){return!1}},Wa={};
Wa.i=new Ua(function(a,b,c){for(var d=0;d<b.length;d+=1){var e=b[d],f;f=e;f=a.replace(/(-1|-2)$/,"").slice(0,28)+"-"+f;c.push(new Ia(f,[e]))}a={};for(e=0;e<b.length;e++)c=b[e],d=c.charAt(1),(a[d]||(a[d]=[])).push(c);c=[[4,3,2,1,5,6,7,8,9],[7,8,9,6,5,4,3,2,1]];d=[];for(e=0;e<c.length;e++){f=c[e];for(var g=0;g<f.length;g++){var m=f[g];if(a[m]){d=d.concat(a[m]);break}}}c=d;d={};a=[];for(e=0;e<c.length;e++)f=c[e],d[f]||(d[f]=!0,a.push(f));c=[];for(d=0;d<b.length;d++)for(e=b[d],f=0;f<a.length;f++)g=a[f],
g==e&&c.push(g);return c});var T={};T.a=T.j=T.b=T.d=T.j=function(){return[]};T.i=function(a,b,c){return[new Ca(a),new Da(b,c)]};T.k=function(a){return[new Ca(a)]};function Xa(a,b,c){return T[b](a,b,c)}function U(a){this.g=a;this.s="x";this.fa=this.e=null;this.t=[];this.P=[];this.X=null}U.prototype.supportsConfiguredBrowser=function(){return"x"!==this.s};
U.prototype.init=function(){if(0<this.P.length){for(var a=[],b=0;b<this.P.length;b++)a.push(Ba(this.P[b]));var b=this.g,a=a.join(""),c=this.g.createElement("style");c.setAttribute("type","text/css");c.styleSheet?c.styleSheet.cssText=a:c.appendChild(document.createTextNode(a));k(b,"head",c)}};
U.prototype.load=function(a,b,c,d,e){if(this.s){for(var f=Wa[this.s]||new Ua(Va),g=0;g<this.t.length;g++)Ga(this.t[g],this.s,f);this.X&&(f=Xa(this.g,this.s,this.t),f=Ea(this.s,f),e&&(f.contextPath=e),e=this.X.l("https:"===n(this.g),f),ja(this.g,e));if(c){for(var m=[],v={},q=new ya(this.e,this.g,b,d),g=0;g<this.t.length;g++)m=m.concat(Ha(this.t[g],this.s));for(g=0;g<m.length;g++)v[m[g].getName()]="BESbswy\ue000\ue001\ue002\ue003\ue004\ue005\ue006";ea(this.g,function(){var b=m,c={},d=v||{};if(0===b.length&&
a)D(q.C);else{q.Y+=b.length;a&&(q.ma=a);for(var e=0;e<b.length;e++){var f=b[e],g=d[f.getName()],z=q.C,ha=f;z.F&&l(z.q,[z.o.l(z.p,ha.getName(),F(ha).toString(),"loading")]);E(z,"fontloading",ha);z=null;z=new ta(h(q.Aa,q),h(q.Ba,q),q.g,f,q.B,q.ba,c,g);z.start()}}})}}};U.prototype.performOptionalActions=function(a){this.pa&&ea(this.g,function(a,c,d,e){return function(){a.pa.send(e)}}(this,a,this.e,this.g))};
function Ya(a,b,c,d){this.Fa=a;this.ga=null;this.ta=this.Z=!0;this.g=b;this.e=c;this.q=d;this.u=[]}Ya.prototype.ya=function(a){this.u.push(a)};Ya.prototype.load=function(a,b){var c=a,d=b||{};"string"==typeof c?c=[c]:c&&c.length||(d=c||{},c=[]);d.protocol&&ga(this.g,d.protocol);if(c.length)for(var e=this,f=c.length,g=0;g<c.length;g++)Za(this,c[g],function(){0==--f&&$a(e,d)});else $a(this,d)};function Za(a,b,c){b=a.Fa.l("https:"===n(a.g),{id:encodeURIComponent(b)});ka(a.g,b,c)}
function $a(a,b){if(0!=a.u.length){a.ga=b.contextPath||".";a.Z=!1!==b.events;a.ta=!1!==b.classes;for(var c=new qa(a.g,a.q,b,a.Z,a.ta),d=!1,e=0;e<a.u.length;e++)a.u[e].init(),d=d||a.u[e].supportsConfiguredBrowser();if(d)for(c.F&&l(c.q,[c.o.l(c.p,"loading")]),E(c,"loading"),d=b.timeout,e=0;e<a.u.length;e++){var f=a.u[e];f.supportsConfiguredBrowser()&&(f.load(e==a.u.length-1,c,a.Z,d,a.ga),f.performOptionalActions(window))}else D(c);a.u=[]}}var ab=(new ma(navigator.userAgent,document)).parse(),bb=new da(window);
window.Typekit||(window.Typekit={});if(!window.Typekit.load){var cb=window.Typekit.config||{},db=null;cb.k&&(db=new L(cb.k));var V=new Ya(db,bb,ab,document.documentElement);window.Typekit.load=function(){V.load.apply(V,arguments)};window.Typekit.addKit=function(){V.ya.apply(V,arguments)}}var eb,W,X,J=window.Typekit.config||{};X=new U(bb);X.pa=new Ja(J.ps,J.ht,J.fi,J.a,J.kt);W=new La;W.la=!J.si;W.T=!J.st;W.G=!J.sa;W.wa=!J.sw;W.ea=!J.sb;X.fa=W;J.f&&(eb=new L(J.f),X.X=eb);var K;
if(J.fn)for(K=0;K<J.fn.length;K+=2)X.t.push(new Fa(J.fn[K],J.fn[K+1]));if(J.c)for(K=0;K<J.c.length;K+=2)X.P.push(new Aa);X.e=ab;var Y;a:{var fb=X.e,gb=new La,hb=X.fa||gb,Z;for(Z in R){var $=R[Z];if(S[$]&&S[$](fb,hb)){Y=$;break a}}for(Z in R)if($=R[Z],S[$]&&S[$](fb,gb)){Y="x";break a}Y="k"}X.s=Y;window.Typekit.addKit(X);if(window.WebFont)try{window.Typekit.load()}catch(ib){};
})(this,document);
